/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ta_inventaris_toko;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;


/**
 *
 * @author chris
 */
public class tambahProduk extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form tambahProduk
     */
    Database data = new Database();
    
    public tambahProduk() {
        initComponents();
        initSettings();
        updateTable();
    }
    
    private void initSettings() {
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANELATAS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KOTAKPENCARIAN = new javax.swing.JTextField();
        btCARI = new javax.swing.JButton();
        PANELBAWAH = new javax.swing.JPanel();
        NAMAPRODUK = new javax.swing.JLabel();
        KOTAKNAMAPRODUK = new javax.swing.JTextField();
        JUMLAH = new javax.swing.JLabel();
        KOTAKJUMLAH = new javax.swing.JTextField();
        btTambah = new javax.swing.JButton();
        btKembali = new javax.swing.JButton();
        HAGRA = new javax.swing.JLabel();
        KOTAKHARGA = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABEL = new javax.swing.JTable();
        btHAPUS = new javax.swing.JButton();
        btREFRESH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PANELATAS.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INVENTARIS TOKOKU");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tambah Produk");

        KOTAKPENCARIAN.setBackground(new java.awt.Color(255, 255, 0));
        KOTAKPENCARIAN.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        KOTAKPENCARIAN.setForeground(new java.awt.Color(0, 0, 0));
        KOTAKPENCARIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOTAKPENCARIANActionPerformed(evt);
            }
        });

        btCARI.setBackground(new java.awt.Color(255, 255, 0));
        btCARI.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btCARI.setForeground(new java.awt.Color(0, 0, 0));
        btCARI.setText("Cari");
        btCARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCARIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANELATASLayout = new javax.swing.GroupLayout(PANELATAS);
        PANELATAS.setLayout(PANELATASLayout);
        PANELATASLayout.setHorizontalGroup(
            PANELATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELATASLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(417, Short.MAX_VALUE))
            .addGroup(PANELATASLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCARI, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KOTAKPENCARIAN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        PANELATASLayout.setVerticalGroup(
            PANELATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELATASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(PANELATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KOTAKPENCARIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCARI)))
        );

        PANELBAWAH.setBackground(new java.awt.Color(255, 0, 255));

        NAMAPRODUK.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        NAMAPRODUK.setForeground(new java.awt.Color(0, 0, 0));
        NAMAPRODUK.setText("Nama Produk :");

        KOTAKNAMAPRODUK.setBackground(new java.awt.Color(255, 255, 0));
        KOTAKNAMAPRODUK.setForeground(new java.awt.Color(0, 0, 0));
        KOTAKNAMAPRODUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOTAKNAMAPRODUKActionPerformed(evt);
            }
        });

        JUMLAH.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        JUMLAH.setForeground(new java.awt.Color(0, 0, 0));
        JUMLAH.setText("Jumlah :");

        KOTAKJUMLAH.setBackground(new java.awt.Color(255, 255, 0));
        KOTAKJUMLAH.setForeground(new java.awt.Color(0, 0, 0));
        KOTAKJUMLAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOTAKJUMLAHActionPerformed(evt);
            }
        });

        btTambah.setBackground(new java.awt.Color(255, 255, 0));
        btTambah.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btTambah.setForeground(new java.awt.Color(0, 0, 0));
        btTambah.setText("Tambah");
        btTambah.setToolTipText("");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        btKembali.setBackground(new java.awt.Color(255, 255, 0));
        btKembali.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btKembali.setForeground(new java.awt.Color(0, 0, 0));
        btKembali.setText("Kembali");
        btKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKembaliActionPerformed(evt);
            }
        });

        HAGRA.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        HAGRA.setForeground(new java.awt.Color(0, 0, 0));
        HAGRA.setText("Harga :");

        KOTAKHARGA.setBackground(new java.awt.Color(255, 255, 0));
        KOTAKHARGA.setForeground(new java.awt.Color(0, 0, 0));
        KOTAKHARGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOTAKHARGAActionPerformed(evt);
            }
        });

        TABEL.setBackground(new java.awt.Color(153, 153, 255));
        TABEL.setForeground(new java.awt.Color(0, 0, 0));
        TABEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nama", "Jumlah", "Harga"
            }
        ));
        TABEL.setGridColor(new java.awt.Color(255, 255, 0));
        TABEL.setSelectionBackground(new java.awt.Color(255, 0, 0));
        TABEL.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(TABEL);

        btHAPUS.setBackground(new java.awt.Color(255, 255, 0));
        btHAPUS.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btHAPUS.setForeground(new java.awt.Color(0, 0, 0));
        btHAPUS.setText("Hapus");
        btHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHAPUSActionPerformed(evt);
            }
        });

        btREFRESH.setBackground(new java.awt.Color(255, 255, 0));
        btREFRESH.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btREFRESH.setForeground(new java.awt.Color(0, 0, 0));
        btREFRESH.setText("Clear");
        btREFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btREFRESHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANELBAWAHLayout = new javax.swing.GroupLayout(PANELBAWAH);
        PANELBAWAH.setLayout(PANELBAWAHLayout);
        PANELBAWAHLayout.setHorizontalGroup(
            PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELBAWAHLayout.createSequentialGroup()
                .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELBAWAHLayout.createSequentialGroup()
                        .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANELBAWAHLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(HAGRA)
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELBAWAHLayout.createSequentialGroup()
                                .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JUMLAH)
                                    .addComponent(NAMAPRODUK))
                                .addGap(18, 18, 18)))
                        .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KOTAKNAMAPRODUK, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(KOTAKJUMLAH)
                            .addComponent(KOTAKHARGA)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELBAWAHLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btREFRESH)))
                .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANELBAWAHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                        .addComponent(btKembali)
                        .addGap(50, 50, 50))
                    .addGroup(PANELBAWAHLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PANELBAWAHLayout.setVerticalGroup(
            PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELBAWAHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANELBAWAHLayout.createSequentialGroup()
                        .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NAMAPRODUK)
                            .addComponent(KOTAKNAMAPRODUK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JUMLAH)
                            .addComponent(KOTAKJUMLAH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HAGRA)
                            .addComponent(KOTAKHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANELBAWAHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(PANELBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTambah)
                            .addComponent(btHAPUS)
                            .addComponent(btREFRESH))
                        .addGap(30, 30, 30))
                    .addGroup(PANELBAWAHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PANELATAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PANELBAWAH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANELATAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PANELBAWAH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KOTAKJUMLAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOTAKJUMLAHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KOTAKJUMLAHActionPerformed

    private void btKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembaliActionPerformed
        // TODO add your handling code here:
        new TA_INVENTARIS_TOKO().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btKembaliActionPerformed
    
    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
    String nama = KOTAKNAMAPRODUK.getText();
    String jumlahInput = KOTAKJUMLAH.getText();
    String hargaInput = KOTAKHARGA.getText();

    if (evt.getSource() == btTambah) {
        if (nama.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan masukkan nama produk dengan benar!!!");
            return;
        }
            // Check if the first letter is a hyphen (-)
        if (nama.charAt(0) == '-') {
            JOptionPane.showMessageDialog(null, "Nama produk tidak boleh dimulai dengan tanda strip (-)!!!");
            return;
        }
        int jumlah = 0;
        if (!jumlahInput.isEmpty() && jumlahInput.matches("\\d++")) {
            jumlah = Integer.parseInt(jumlahInput);
            if (jumlah <= 0) {
                JOptionPane.showMessageDialog(null, "Masukkan jumlah dengan benar (angka harus lebih dari 0)!!!");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan jumlah dengan benar!!!");
            return;
        }

        int harga = 0;
        if (!hargaInput.isEmpty() && hargaInput.matches("\\d++")) {
            harga = Integer.parseInt(hargaInput);
            if (harga <= 0) {
                JOptionPane.showMessageDialog(null, "Masukkan Harga dengan benar (angka harus lebih dari 0)!!!");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan Harga dengan benar!!!");
            return;
        }

        if (data.isProdukExists(nama)) {
            JOptionPane.showMessageDialog(null, "Produk yang sama telah ada dalam daftar");
            return;
        }

        data.addProduk(nama, jumlah, harga);
        updateTable();

        // Bersihkan nilai yang dimasukkan pengguna
        KOTAKNAMAPRODUK.setText("");
        KOTAKJUMLAH.setText("");
        KOTAKHARGA.setText("");
    }
        
    }//GEN-LAST:event_btTambahActionPerformed

    
private void updateTable() {
    DefaultTableModel model = (DefaultTableModel) TABEL.getModel();
    model.setRowCount(0); // Menghapus semua baris pada tabel

    String[] produkList = data.getProduk();
    Integer[] jumlahProdukList = data.getJumlahProduk();
    Integer[] hargaProdukList = data.getHargaProduk();

    for (int i = 0; i < produkList.length; i++) {
        String produk = produkList[i];
        int jumlahProduk = jumlahProdukList[i];
        int hargaProduk = hargaProdukList[i];

        Object[] row = { produk, jumlahProduk, hargaProduk };
        model.addRow(row);
    }
}

        
        
    private void KOTAKHARGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOTAKHARGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KOTAKHARGAActionPerformed

    private void KOTAKNAMAPRODUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOTAKNAMAPRODUKActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_KOTAKNAMAPRODUKActionPerformed

    private void btHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHAPUSActionPerformed
        // TODO add your handling code here:
    int selectedRow = TABEL.getSelectedRow();
    
    // Memastikan ada baris yang dipilih
    if (selectedRow >= 0) {
        // Menghapus baris yang dipilih dari tabel
        DefaultTableModel model = (DefaultTableModel) TABEL.getModel();
        String produk = (String) model.getValueAt(selectedRow, 0);
        model.removeRow(selectedRow);

        // Menghapus produk dari database
        data.deleteProduk(produk);

        updateTable();
    }
    }//GEN-LAST:event_btHAPUSActionPerformed

    private void btREFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btREFRESHActionPerformed
        // TODO add your handling code here:\
        KOTAKNAMAPRODUK.setText("");
        KOTAKJUMLAH.setText("");
        KOTAKHARGA.setText("");
            updateTable();
    }//GEN-LAST:event_btREFRESHActionPerformed

    private void KOTAKPENCARIANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOTAKPENCARIANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KOTAKPENCARIANActionPerformed

    private void btCARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCARIActionPerformed
        
    String kataKunci = KOTAKPENCARIAN.getText(); // Kata kunci yang dimasukkan oleh pengguna
    String[] hasilPencarian = data.cariProduk(kataKunci);

    // Lakukan sesuatu dengan hasil pencarian, misalnya menampilkan pada GUI atau melakukan operasi lainnya
    DefaultTableModel model = (DefaultTableModel) TABEL.getModel();
    model.setRowCount(0); // Menghapus semua baris pada tabel

    for (String produk : hasilPencarian) {
        int index = Arrays.asList(data.getProduk()).indexOf(produk); // Temukan indeks produk dalam array produk dari Database
        int jumlahProduk = data.getJumlahProduk()[index];
        int hargaProduk = data.getHargaProduk()[index];

        Object[] row = { produk, jumlahProduk, hargaProduk };
        model.addRow(row);
    }
    
    
    }//GEN-LAST:event_btCARIActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HAGRA;
    private javax.swing.JLabel JUMLAH;
    private javax.swing.JTextField KOTAKHARGA;
    private javax.swing.JTextField KOTAKJUMLAH;
    private javax.swing.JTextField KOTAKNAMAPRODUK;
    private javax.swing.JTextField KOTAKPENCARIAN;
    private javax.swing.JLabel NAMAPRODUK;
    private javax.swing.JPanel PANELATAS;
    private javax.swing.JPanel PANELBAWAH;
    private javax.swing.JTable TABEL;
    private javax.swing.JButton btCARI;
    private javax.swing.JButton btHAPUS;
    private javax.swing.JButton btKembali;
    private javax.swing.JButton btREFRESH;
    private javax.swing.JButton btTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

